#!/usr/bin/env python3
"""Brandstore demo build (python3 stdlib only).

Usage:
    python3 build.py                     build every src/pages/*.html (files starting with "_" are skipped)
    python3 build.py --include-private   also build "_*.html" pages (e.g. _kitchen-sink.html)
    python3 build.py --only index        build only src/pages/index.html
    python3 build.py --fetch-icons       re-download the Phosphor sprite + Simple Icons payment marks, then build

What it does:
  1. runs every src/generators/*.py (they may write pages into src/pages/)
  2. for each page: parses the first-line meta comment
        <!-- @page title="..." description="..." body="page-home" header="overlay" css="home" js="home"
                   nav="home" mobilebar="on" preload="assets/media/hero-poster.jpg" og_image="..." -->
     resolves <!-- @include name --> (src/partials/name.html or .svg, recursive),
     wraps the page body with the shared partials and writes <project root>/<name>.html
  3. mega menus, brands panel and mobile menu drawer are rendered statically from assets/data/catalog.js,
     so navigation works without JavaScript.
"""
from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import subprocess
import sys
import unicodedata
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
PARTIALS = SRC / "partials"
PAGES = SRC / "pages"
GENERATORS = SRC / "generators"
CATALOG_JS = ROOT / "assets" / "data" / "catalog.js"

NBSP = " "

# ---------------------------------------------------------------- icons ----
# Phosphor LIGHT icons, symbol id = "i-<name>". Add a name here and run --fetch-icons.
ICONS_LIGHT = [
    "magnifying-glass", "user", "heart", "handbag", "handbag-simple", "x", "list", "caret-down", "caret-up",
    "caret-left", "caret-right", "arrow-right", "arrow-left", "arrow-up", "arrow-down", "arrow-up-right",
    "plus", "minus", "check", "truck", "arrow-counter-clockwise", "shield-check", "seal-check", "seal-percent",
    "credit-card", "eye", "sliders-horizontal", "funnel", "squares-four", "rows", "grid-four", "square",
    "columns", "star", "play", "pause", "house", "tag", "percent", "phone", "envelope-simple", "envelope",
    "map-pin", "instagram-logo", "facebook-logo", "ruler", "package", "clock", "clock-counter-clockwise",
    "sparkle", "trash", "trend-up", "lock-simple", "check-circle", "warning-circle", "info", "storefront",
    "bell", "quotes", "arrows-out-simple", "magnifying-glass-plus", "t-shirt", "sneaker", "coat-hanger",
    "dress", "hoodie", "pants", "boot", "baby", "backpack", "eyeglasses", "wallet", "crown-simple", "diamond",
    "gift", "share-network", "x-circle", "dots-three", "arrow-square-out", "timer", "hand-tap", "keyboard",
]
# Phosphor FILL icons, symbol id = "i-<name>-fill"
ICONS_FILL = ["heart", "star", "play", "pause", "quotes", "check-circle", "seal-check"]
# Only the methods the current store names (Apple Pay, Google Pay, el. bankininkystė). Add ("visa", "Visa"), ("mastercard", "Mastercard") if the client confirms cards.
PAYMENT_MARKS = [("applepay", "Apple Pay"), ("googlepay", "Google Pay")]

PHOSPHOR = "https://cdn.jsdelivr.net/npm/@phosphor-icons/core@2/assets/{weight}/{name}{suffix}.svg"


def _get(url: str) -> str:
    """Download text. Falls back to the system curl when Python has no CA bundle (python.org builds on macOS)."""
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "brandstore-build/1.0"})
        with urllib.request.urlopen(req, timeout=30) as r:
            return r.read().decode("utf-8")
    except Exception:  # noqa: BLE001
        res = subprocess.run(["curl", "-sfL", "--max-time", "30", url], capture_output=True)
        if res.returncode != 0:
            raise RuntimeError(f"download failed: {url}")
        return res.stdout.decode("utf-8")


def fetch_icons() -> None:
    symbols, missing = [], []
    jobs = [(n, "light", "-light", f"i-{n}") for n in ICONS_LIGHT] + [(n, "fill", "-fill", f"i-{n}-fill") for n in ICONS_FILL]
    for name, weight, suffix, sid in jobs:
        try:
            svg = _get(PHOSPHOR.format(weight=weight, name=name, suffix=suffix))
        except Exception as exc:  # noqa: BLE001
            missing.append(f"{weight}/{name} ({exc})")
            continue
        vb = re.search(r'viewBox="([^"]+)"', svg)
        inner = re.sub(r"^.*?<svg[^>]*>|</svg>\s*$", "", svg.strip(), flags=re.S)
        symbols.append(f'<symbol id="{sid}" viewBox="{vb.group(1) if vb else "0 0 256 256"}">{inner}</symbol>')
    if not symbols:
        raise SystemExit("icons: nothing downloaded, keeping the existing sprite")
    sprite = (
        "<!-- Phosphor Icons (light + fill), MIT, https://phosphoricons.com. Generated by build.py --fetch-icons -->\n"
        '<svg xmlns="http://www.w3.org/2000/svg" class="icon-sprite" aria-hidden="true" focusable="false" '
        'style="position:absolute;width:0;height:0;overflow:hidden">\n' + "\n".join(symbols) + "\n</svg>\n"
    )
    (PARTIALS / "icons.svg").write_text(sprite, encoding="utf-8")
    print(f"icons: {len(symbols)} symbols -> src/partials/icons.svg")
    if missing:
        print("icons: MISSING " + ", ".join(missing))

    marks = []
    for slug, label in PAYMENT_MARKS:
        svg = _get(f"https://cdn.simpleicons.org/{slug}")
        inner = re.sub(r"^.*?<svg[^>]*>|</svg>\s*$", "", svg.strip(), flags=re.S)
        inner = re.sub(r"<title>.*?</title>", "", inner, flags=re.S)
        marks.append(
            f'<li class="pay-mark" title="{label}"><svg class="pay-mark__svg" viewBox="0 0 24 24" role="img" '
            f'aria-label="{label}" fill="currentColor">{inner}</svg></li>'
        )
    marks.append('<li class="pay-mark pay-mark--text">El. bankininkystė</li>')
    (PARTIALS / "payment-marks.html").write_text(
        "<!-- Simple Icons (CC0), https://simpleicons.org. Generated by build.py --fetch-icons -->\n"
        + "\n".join(marks) + "\n", encoding="utf-8")
    print("payments: src/partials/payment-marks.html")


# --------------------------------------------------------------- helpers ----
def esc(s) -> str:
    return html.escape(str(s), quote=True)


def fmt_num(n) -> str:
    s = f"{int(round(n)):,}".replace(",", NBSP)
    return s


def plural(n: int, forms) -> str:
    n = abs(int(n))
    if n % 10 == 1 and n % 100 != 11:
        return forms[0]
    if 2 <= n % 10 <= 9 and not 11 <= n % 100 <= 19:
        return forms[1]
    return forms[2]


def norm(s: str) -> str:
    return "".join(c for c in unicodedata.normalize("NFD", s) if unicodedata.category(c) != "Mn").lower()


def url(params: dict) -> str:
    from urllib.parse import urlencode
    return "parduotuve.html?" + esc(urlencode(params))


def icon(name: str, cls: str = "") -> str:
    c = f"i {cls}".strip()
    return f'<svg class="{c}" aria-hidden="true" focusable="false"><use href="#i-{name}"></use></svg>'


ACC_ICON = '<span class="acc__icon" aria-hidden="true">' + icon("plus", "acc__plus") + icon("minus", "acc__minus") + "</span>"


def load_catalog() -> dict:
    js = CATALOG_JS.read_text(encoding="utf-8")
    start = js.index("=") + 1
    return json.loads(js[start:].strip().rstrip(";"))


def file_version(rel: str) -> str:
    p = ROOT / rel
    if not p.exists():
        return "0"
    return hashlib.md5(p.read_bytes()).hexdigest()[:8]


# ------------------------------------------------------- static nav render ----
GENDER_LABEL = {"moterims": "Moterims", "vyrams": "Vyrams", "vaikams": "Vaikams"}
PROMO = {
    "moterims": ("assets/media/jai.jpg", "Išpardavimas moterims", "55% 35%"),
    "vyrams": ("assets/media/jam.jpg", "Išpardavimas vyrams", "50% 30%"),
    "vaikams": ("assets/media/vaikams.jpg", "Išpardavimas vaikams", "48% 55%"),
}
COLUMN_ORDER = ["Drabužiai", "Avalynė", "Aksesuarai"]
ALL_LABEL = {"Drabužiai": "Visi drabužiai", "Avalynė": "Visa avalynė", "Aksesuarai": "Visi aksesuarai"}


def popular_brands(cat: dict, gender: str, n: int = 8) -> list:
    """Brands that have items of that gender in the sale listing (BS.collections.plp), because every listing link
    lands on the sale page. Ranked by that count, then by the store 'top' flag and the real store count."""
    plp = set(cat.get("collections", {}).get("plp") or [])
    counts = {}
    for p in cat["products"]:
        if p["gender"] == gender and p["id"] in plp:
            counts[p["brandSlug"]] = counts.get(p["brandSlug"], 0) + 1
    ranked = sorted(
        (b for b in cat["brands"] if counts.get(b["slug"])),
        key=lambda b: (-counts[b["slug"]], not b.get("top"), -(b.get("count") or 0)),
    )
    return ranked[:n]


def demo_brand_slugs(cat: dict) -> set:
    """Brand slugs that have at least one product in the demo data (BS.products)."""
    return {p["brandSlug"] for p in cat["products"]}


def render_mega_panel(item: dict, cat: dict) -> str:
    gender = item["slug"]
    cols_html = []
    i = 0
    columns = item["columns"]
    if gender != "vaikams":
        columns = sorted(columns, key=lambda c: COLUMN_ORDER.index(c["label"]) if c["label"] in COLUMN_ORDER else 9)
    for col in columns:
        items = sorted(col["items"], key=lambda x: -(x.get("count") or 0))
        is_clothes = col["label"] == "Drabužiai" and gender != "vaikams"
        limit = 12 if is_clothes else 8
        shown = items[:limit]
        lis = "".join(
            f'<li><a class="mega__link" href="{url({"lytis": gender, "kategorija": it["slug"]})}">'
            f'<span>{esc(it["label"])}</span>'
            + (f'<span class="mega__count">{fmt_num(it["count"])}</span>' if it.get("count") else "")
            + "</a></li>"
            for it in shown
        )
        if gender == "vaikams":
            col_href = url({"lytis": "vaikams", "kategorija": col["slug"]})
            all_label = f"Visos prekės {col['label'].lower()}"
        else:
            col_href = url({"lytis": gender, "kategorija": col["slug"]})
            all_label = ALL_LABEL.get(col["label"], "Visos prekės")
        count = f'<span class="mega__count">{fmt_num(col["count"])}</span>' if col.get("count") else ""
        cls = "mega__col mega__col--wide" if is_clothes else "mega__col"
        cols_html.append(
            f'<div class="{cls}" style="--i:{i}">'
            f'<p class="mega__title"><a href="{col_href}">{esc(col["label"])}</a>{count}</p>'
            f'<ul class="mega__list{" mega__list--split" if is_clothes else ""}" role="list">{lis}</ul>'
            f'<a class="mega__all" href="{col_href}">{esc(all_label)}{icon("arrow-right", "i--xs")}</a>'
            "</div>"
        )
        i += 1
    brands = popular_brands(cat, gender)
    blis = "".join(
        f'<li><a class="mega__link" href="{url({"lytis": gender, "zenklas": b["slug"]})}"><span>{esc(b["name"])}</span></a></li>'
        for b in brands
    )
    cols_html.append(
        f'<div class="mega__col" style="--i:{i}"><p class="mega__title">Populiarūs prekių ženklai</p>'
        f'<ul class="mega__list" role="list">{blis}</ul>'
        f'<button class="mega__all" type="button" data-open-brands>Visi prekių ženklai A-Z{icon("arrow-right", "i--xs")}</button></div>'
    )
    img, title, focal = PROMO[gender]
    promo = (
        f'<a class="mega__promo" href="{url({"lytis": gender})}" style="--i:{i + 1}">'
        f'<span class="mega__promo-media"><img src="{img}" alt="" loading="lazy" decoding="async" width="1067" height="1600" style="object-position:{focal}"></span>'
        f'<span class="mega__promo-body"><span class="mega__promo-title">{esc(title)}</span>'
        f'<span class="mega__promo-link">Žiūrėti visus pasiūlymus{icon("arrow-right", "i--sm")}</span></span></a>'
    )
    total = item.get("count")
    foot = (
        f'<div class="mega__foot"><a class="mega__foot-link" href="{url({"lytis": gender})}">Visos prekės {esc(GENDER_LABEL[gender].lower())}'
        + (f' <span class="mega__count">{fmt_num(total)}</span>' if total else "")
        + f'{icon("arrow-right", "i--sm")}</a>'
        f'<a class="mega__foot-link" href="index.html#naujienos">Naujienos</a>'
        f'<a class="mega__foot-link mega__foot-link--sale" href="{url({"lytis": gender})}">Išpardavimas {esc(GENDER_LABEL[gender].lower())}</a></div>'
    )
    return (
        f'<div class="mega mega--{gender}" id="mega-{gender}" data-mega data-lenis-prevent>'
        f'<div class="mega__inner container"><div class="mega__grid mega__grid--{len(cols_html)}">{"".join(cols_html)}{promo}</div>{foot}</div></div>'
    )


def brand_letter(name: str) -> str:
    ch = norm(name)[:1].upper()
    return ch if ch.isalpha() else "#"


def render_brand_list(brands: list, id_prefix: str, demo: set | None = None) -> str:
    """A-Z brand list. Letters are plain text in a labelled group (not headings), so the header does not put
    19 hidden h3s in front of the page h1. Brands without any demo product keep their real listing link
    (works without JS) but get data-demo-brand: core shows a toast instead of an empty listing."""
    groups: dict[str, list] = {}
    for b in sorted(brands, key=lambda b: norm(b["name"])):
        groups.setdefault(brand_letter(b["name"]), []).append(b)
    out = []
    for letter, items in groups.items():
        lis = "".join(
            f'<li data-brand="{esc(norm(b["name"]))}"><a class="brand-list__link'
            + (f'" href="{url({"zenklas": b["slug"]})}">' if demo is None or b["slug"] in demo
               else f' is-demo-empty" href="{url({"zenklas": b["slug"]})}" data-demo-brand="{esc(b["name"])}">')
            + f'<span>{esc(b["name"])}</span>'
            + (f'<span class="mega__count">{fmt_num(b["count"])}</span>' if b.get("count") else "")
            + "</a></li>"
            for b in items
        )
        out.append(
            f'<div class="brand-group" role="group" data-letter="{letter}" id="{id_prefix}-{letter}" aria-label="{letter}">'
            f'<p class="brand-group__letter" aria-hidden="true">{letter}</p><ul class="brand-group__list" role="list">{lis}</ul></div>'
        )
    return "".join(out), set(groups)


DEMO_BRANDS_NOTE = (
    '<p class="brands-panel__note">Pilkai pažymėtų prekių ženklų prekės į demo versiją neįtrauktos.</p>'
)


def render_brands_panel(cat: dict) -> str:
    brands = cat["brands"]
    list_html, letters = render_brand_list(brands, "zenklai", demo_brand_slugs(cat))
    az = "".join(
        (f'<button class="az__btn" type="button" data-az="{L}" aria-label="Prekių ženklai iš raidės {L}">{L}</button>'
         if L in letters else f'<span class="az__btn is-disabled" aria-hidden="true">{L}</span>')
        for L in "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    )
    top = [b for b in brands if b.get("top")]
    top.sort(key=lambda b: -(b.get("count") or 0))
    chips = "".join(f'<li><a class="chip chip--sm" href="{url({"zenklas": b["slug"]})}">{esc(b["name"])}</a></li>' for b in top)
    return (
        '<div class="mega mega--brands" id="mega-zenklai" data-mega data-brands-panel data-lenis-prevent>'
        '<div class="mega__inner container"><div class="brands-panel">'
        '<div class="brands-panel__top" style="--i:0">'
        '<div class="search-field search-field--line"><label class="sr-only" for="brand-filter">Raskite prekės ženklą</label>'
        f'{icon("magnifying-glass", "search-field__icon")}'
        '<input class="search-field__input" id="brand-filter" type="search" placeholder="Raskite prekės ženklą" autocomplete="off" data-brand-filter></div>'
        f'<nav class="az" aria-label="Prekių ženklai pagal raidę">{az}</nav></div>'
        f'<div class="brands-panel__popular" style="--i:1"><p class="mega__title">Populiariausi</p><ul class="chips" role="list">{chips}</ul></div>'
        f'<div class="brands-panel__list brand-list" data-brand-list style="--i:2">{list_html}</div>'
        '<p class="brands-panel__empty" data-brand-empty hidden></p>'
        f'{DEMO_BRANDS_NOTE}'
        f'</div></div></div>'
    )


def render_nav(cat: dict, active: str) -> str:
    nav = {n["label"]: n for n in cat["nav"]}

    def cur(key):
        return ' aria-current="page"' if key == active else ""

    items = [f'<li class="nav__item"><a class="nav__link" href="index.html#naujienos"{cur("naujienos")}>Naujienos</a></li>']
    for label in ("Moterims", "Vyrams", "Vaikams"):
        it = nav[label]
        g = it["slug"]
        items.append(
            f'<li class="nav__item nav__item--mega">'
            f'<button class="nav__link" type="button" aria-expanded="false" aria-controls="mega-{g}" data-mega-trigger{cur(g)}>'
            f'{esc(label)}{icon("caret-down", "i--xs nav__caret")}</button>{render_mega_panel(it, cat)}</li>'
        )
    items.append(
        '<li class="nav__item nav__item--mega">'
        f'<button class="nav__link" type="button" aria-expanded="false" aria-controls="mega-zenklai" data-mega-trigger{cur("zenklai")}>'
        f'Prekių ženklai{icon("caret-down", "i--xs nav__caret")}</button>{render_brands_panel(cat)}</li>'
    )
    items.append(f'<li class="nav__item"><a class="nav__link" href="index.html#dizaineriu-kolekcija"{cur("dizaineriai")}>Dizainerių kolekcija</a></li>')
    items.append(
        f'<li class="nav__item"><a class="nav__link nav__link--sale" href="parduotuve.html"{cur("ispardavimas")}>'
        f'Išpardavimas<span class="nav__pct" aria-hidden="true">%</span></a></li>'
    )
    return '<ul class="nav" role="list">' + "".join(items) + "</ul>"


def render_menu_drawer(cat: dict) -> str:
    nav = {n["label"]: n for n in cat["nav"]}
    tabs, panels = [], []
    for idx, label in enumerate(("Moterims", "Vyrams", "Vaikams")):
        it = nav[label]
        g = it["slug"]
        sel = idx == 0
        tabs.append(
            f'<button class="tabs__btn" type="button" role="tab" id="md-tab-{g}" aria-controls="md-panel-{g}" '
            f'aria-selected="{"true" if sel else "false"}" tabindex="{0 if sel else -1}">{esc(label)}</button>'
        )
        cols = it["columns"]
        if g != "vaikams":
            cols = sorted(cols, key=lambda c: COLUMN_ORDER.index(c["label"]) if c["label"] in COLUMN_ORDER else 9)
        accs = []
        for col in cols:
            items = sorted(col["items"], key=lambda x: -(x.get("count") or 0))
            lis = "".join(
                f'<li><a class="mdrawer__link" href="{url({"lytis": g, "kategorija": x["slug"]})}">{esc(x["label"])}'
                + (f'<span class="mega__count">{fmt_num(x["count"])}</span>' if x.get("count") else "")
                + "</a></li>"
                for x in items
            )
            all_label = f"Visos prekės {col['label'].lower()}" if g == "vaikams" else ALL_LABEL.get(col["label"], "Visos prekės")
            lis += f'<li><a class="mdrawer__link mdrawer__link--all" href="{url({"lytis": g, "kategorija": col["slug"]})}">{esc(all_label)}</a></li>'
            accs.append(
                f'<details class="acc acc--menu"><summary class="acc__head">{esc(col["label"])}'
                f'{ACC_ICON}</summary>'
                f'<div class="acc__body"><ul class="mdrawer__list" role="list">{lis}</ul></div></details>'
            )
        total = f'<span class="mega__count">{fmt_num(it["count"])}</span>' if it.get("count") else ""
        panels.append(
            f'<div class="mdrawer__panel" role="tabpanel" id="md-panel-{g}" aria-labelledby="md-tab-{g}"{"" if sel else " hidden"}>'
            f'<a class="mdrawer__all" href="{url({"lytis": g})}">Visos prekės {esc(label.lower())}{total}</a>'
            + "".join(accs) + "</div>"
        )
    brand_list, _ = render_brand_list(cat["brands"], "md-zenklai", demo_brand_slugs(cat))
    return (
        '<div class="mdrawer__tabs" data-tabs>'
        f'<div class="tabs tabs--full" role="tablist" aria-label="Pasirinkite skyrių">{"".join(tabs)}<span class="tabs__ink" aria-hidden="true"></span></div>'
        + "".join(panels) + "</div>"
        '<ul class="mdrawer__links" role="list">'
        f'<li><details class="acc acc--menu" data-mobile-brands><summary class="acc__head">Prekių ženklai{ACC_ICON}</summary>'
        '<div class="acc__body"><div class="search-field search-field--line mdrawer__brand-search">'
        '<label class="sr-only" for="md-brand-filter">Raskite prekės ženklą</label>'
        f'{icon("magnifying-glass", "search-field__icon")}'
        '<input class="search-field__input" id="md-brand-filter" type="search" placeholder="Raskite prekės ženklą" autocomplete="off" data-brand-filter></div>'
        f'<div class="brand-list brand-list--drawer" data-brand-list>{brand_list}</div><p class="brands-panel__empty" data-brand-empty hidden></p>{DEMO_BRANDS_NOTE}</div></details></li>'
        '<li><a class="mdrawer__item" href="index.html#naujienos">Naujienos</a></li>'
        '<li><a class="mdrawer__item" href="index.html#dizaineriu-kolekcija">Dizainerių kolekcija</a></li>'
        f'<li><a class="mdrawer__item mdrawer__item--sale" href="parduotuve.html">Išpardavimas<span aria-hidden="true">%</span></a></li>'
        "</ul>"
    )


# ------------------------------------------------------------ templating ----
META_RE = re.compile(r"^\s*<!--\s*@page\b(.*?)-->\s*", re.S)
ATTR_RE = re.compile(r'([\w-]+)\s*=\s*"([^"]*)"')
INCLUDE_RE = re.compile(r"<!--\s*@include\s+([\w./-]+)\s*-->")
VAR_RE = re.compile(r"\{\{\s*([\w.-]+)\s*\}\}")


def parse_meta(text: str):
    m = META_RE.match(text)
    if not m:
        return {}, text
    return dict(ATTR_RE.findall(m.group(1))), text[m.end():]


def resolve_includes(text: str, depth: int = 0) -> str:
    if depth > 8:
        raise RuntimeError("include depth exceeded (cycle?)")

    def sub(m):
        name = m.group(1)
        for cand in (PARTIALS / name, PARTIALS / f"{name}.html", PARTIALS / f"{name}.svg"):
            if cand.is_file():
                return resolve_includes(cand.read_text(encoding="utf-8"), depth + 1)
        raise FileNotFoundError(f"@include {name}: no such partial in src/partials/")

    return INCLUDE_RE.sub(sub, text)


def render_vars(text: str, ctx: dict) -> str:
    def sub(m):
        key = m.group(1)
        if key not in ctx:
            raise KeyError(f"template variable {{{{ {key} }}}} is not defined")
        return str(ctx[key])

    return VAR_RE.sub(sub, text)


LAYOUT = """<!doctype html>
<html lang="lt" class="no-js">
<head>
<!-- @include head -->
</head>
<body class="{{ body_class }}">
<!-- @include icons -->
<!-- @include skiplink -->
<!-- @include announcement -->
<!-- @include header -->
<main id="main" class="site-main" tabindex="-1">
{{ page_body }}
</main>
<!-- @include footer -->
{{ mobilebar_html }}
<!-- @include overlays -->
<!-- @include scripts -->
</body>
</html>
"""


def build_page(src: Path, cat: dict, shared: dict) -> Path:
    raw = src.read_text(encoding="utf-8")
    meta, body = parse_meta(raw)
    name = src.stem
    title = meta.get("title", "Brandstore.lt")
    header_mode = meta.get("header", "solid")
    if header_mode not in ("overlay", "solid"):
        raise ValueError(f"{src.name}: header must be overlay|solid")
    nav_key = meta.get("nav", "")
    body_classes = ["page", f"page--{name.lstrip('_')}"]
    if meta.get("body"):
        body_classes.append(meta["body"])
    if header_mode == "overlay":
        body_classes.append("has-overlay-header")
    mobilebar = meta.get("mobilebar", "on") != "off"
    if not mobilebar:
        body_classes.append("no-mobilebar")

    css_tags, js_tags = [], []
    for c in filter(None, (s.strip() for s in meta.get("css", "").split(","))):
        rel = f"assets/css/{c}.css"
        if not (ROOT / rel).exists():
            print(f"  warning: {src.name} links {rel}, which does not exist yet")
        css_tags.append(f'<link rel="stylesheet" href="{rel}?v={file_version(rel)}">')
    for j in filter(None, (s.strip() for s in meta.get("js", "").split(","))):
        rel = f"assets/js/{j}.js"
        if not (ROOT / rel).exists():
            print(f"  warning: {src.name} loads {rel}, which does not exist yet")
        js_tags.append(f'<script defer src="{rel}?v={file_version(rel)}"></script>')
    preload = "".join(
        f'<link rel="preload" as="image" href="{esc(p.strip())}" fetchpriority="high">'
        for p in meta.get("preload", "").split(",") if p.strip()
    )

    mb = resolve_includes("<!-- @include mobilebar -->") if mobilebar else ""
    cur = ' aria-current="page"'
    mb = mb.replace("{{ mb_home }}", cur if nav_key == "home" else "").replace(
        "{{ mb_sale }}", cur if nav_key == "ispardavimas" else "")

    ctx = dict(shared)
    ctx.update(
        title=esc(title),
        description=esc(meta.get("description", "Originalūs drabužiai, avalynė ir aksesuarai iš pasaulio prekių ženklų su nuolaidomis.")),
        og_image=esc(meta.get("og_image", "assets/media/hero-poster.jpg")),
        body_class=" ".join(body_classes),
        header_class="site-header--overlay" if header_mode == "overlay" else "site-header--solid",
        header_mode=header_mode,
        page_css="\n".join(css_tags),
        page_js="\n".join(js_tags),
        preload=preload,
        nav_html=render_nav(cat, nav_key),
        mobilebar_html=mb,
    )
    # page bodies may use shared vars ({{ phone }}, {{ email }} ...); unknown {{ }} are left untouched
    ctx["page_body"] = VAR_RE.sub(lambda m: str(ctx.get(m.group(1), m.group(0))), resolve_includes(body.strip()))
    out = render_vars(resolve_includes(LAYOUT), ctx)
    if "—" in out:
        print(f"  warning: {src.name} contains an em dash (U+2014)")
    dest = ROOT / f"{name}.html"
    old = dest.read_text(encoding="utf-8") if dest.exists() else None
    if old != out:
        dest.write_text(out, encoding="utf-8")
        state = "wrote"
    else:
        state = "unchanged"
    print(f"  {state} {dest.name} ({len(out.encode('utf-8')) // 1024} KB) <- src/pages/{src.name}")
    return dest


def run_generators() -> None:
    if not GENERATORS.is_dir():
        return
    for gen in sorted(GENERATORS.glob("*.py")):
        if gen.name.startswith("_"):
            continue
        print(f"generator: {gen.relative_to(ROOT)}")
        res = subprocess.run([sys.executable, str(gen)], cwd=ROOT)
        if res.returncode != 0:
            raise SystemExit(f"generator {gen.name} failed with exit code {res.returncode}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Assemble src/pages/*.html with src/partials/* into the project root.")
    ap.add_argument("--include-private", action="store_true", help='also build pages whose name starts with "_"')
    ap.add_argument("--only", action="append", default=[], help="build only these page names (repeatable)")
    ap.add_argument("--fetch-icons", action="store_true", help="re-download icon sprite and payment marks first")
    args = ap.parse_args()

    if args.fetch_icons:
        fetch_icons()
    run_generators()
    cat = load_catalog()
    shared = {
        "v_base": file_version("assets/css/base.css"),
        "v_core": file_version("assets/js/core.js"),
        "v_catalog": file_version("assets/data/catalog.js"),
        # images keep their URL when replaced, so the logos carry a content hash too (browsers cache them for 10 min on GitHub Pages)
        "v_logo_dark": file_version("assets/img/brand/logo-dark.png"),
        "v_logo_light": file_version("assets/img/brand/logo-light.png"),
        "menu_drawer_html": render_menu_drawer(cat),
        "phone": esc(cat["meta"]["phone"]),
        "phone_display": esc(cat["meta"]["phoneDisplay"]).replace(" ", NBSP),
        "email": esc(cat["meta"]["email"]),
        "address": esc(cat["meta"]["address"]),
        "year": "2026",
    }
    pages = sorted(PAGES.glob("*.html"))
    if args.only:
        wanted = {o.removesuffix(".html") for o in args.only}
        pages = [p for p in pages if p.stem in wanted]
    elif not args.include_private:
        pages = [p for p in pages if not p.name.startswith("_")]
    if not pages:
        print("no pages to build in src/pages/")
        return
    print(f"building {len(pages)} page(s)")
    for p in pages:
        build_page(p, cat, shared)
    print("done")


if __name__ == "__main__":
    main()
