#!/usr/bin/env python3
"""PDP generator (python3 stdlib only).

Writes src/pages/preke-<slug>.html for every product id in BS.collections.pdp, reading
assets/data/catalog.json. build.py runs this first (cwd = project root), then assembles the pages.

The generated page holds the complete product content as static HTML (gallery, price, sizes,
delivery facts, accordions, JSON-LD), so it reads correctly without JavaScript.
assets/js/pdp.js adds the behaviour: gallery + hover zoom, lightbox, size selection and validation,
add to cart, notify-me form, size guide dialog, delivery estimate, sticky buy bar, and the
cross-sell rows, which are rendered with the core product card (BS.ui.renderProducts).
"""
from __future__ import annotations

import html
import json
import re
from pathlib import Path
from urllib.parse import urlencode

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "assets" / "data" / "catalog.json"
PAGES = ROOT / "src" / "pages"
MARKER = "<!-- Generated by src/generators/pdp.py from assets/data/catalog.json. Edit the generator, not this file. -->"

NBSP = " "
MINUS = "−"

GENDER_LABEL = {"moterims": "Moterims", "vyrams": "Vyrams", "vaikams": "Vaikams"}
GROUP_LABEL = {"drabuziai": "Drabužiai", "avalyne": "Avalynė", "aksesuarai": "Aksesuarai"}

# --------------------------------------------------------------- helpers ----


def esc(s) -> str:
    return html.escape(str(s), quote=True)


def fmt_num(n) -> str:
    return f"{int(round(n)):,}".replace(",", NBSP)


def fmt_price(n) -> str:
    n = float(n)
    if n == int(n):
        return f"{fmt_num(n)}{NBSP}€"
    whole, dec = f"{n:.2f}".split(".")
    return f"{fmt_num(int(whole))},{dec}{NBSP}€"


def discount_label(d) -> str:
    return f"{MINUS}{int(round(abs(d)))}{NBSP}%"


def plural(n: int, forms) -> str:
    n = abs(int(n))
    if n % 10 == 1 and n % 100 != 11:
        return forms[0]
    if 2 <= n % 10 <= 9 and not 11 <= n % 100 <= 19:
        return forms[1]
    return forms[2]


def lc_first(s: str) -> str:
    return s[:1].lower() + s[1:]


def dash_free(s: str) -> str:
    """Same rule as BS.util.dashFree: ' – ' becomes ', ', other dashes become '-'."""
    s = re.sub(r"\s+[–—]\s+", ", ", str(s or ""))
    return re.sub(r"[–—]", "-", s)


def size_label(s: str) -> str:
    return re.sub(r"[–—]", "-", str(s or ""))


def icon(name: str, cls: str = "") -> str:
    c = f"i {cls}".strip()
    return f'<svg class="{c}" aria-hidden="true" focusable="false"><use href="#i-{name}"></use></svg>'


ACC_ICON = '<span class="acc__icon" aria-hidden="true">' + icon("plus", "acc__plus") + icon("minus", "acc__minus") + "</span>"


def listing_url(params: dict) -> str:
    q = {k: v for k, v in params.items() if v not in (None, "", [])}
    return "parduotuve.html" + ("?" + urlencode(q) if q else "")


def image_alt(p: dict) -> str:
    return f"{p['brand']} {lc_first(p['title'])}"


def is_packshot(p: dict, i: int) -> bool:
    if i == 0:
        return p.get("imageBg") == "white"
    return i not in (p.get("modelImages") or [])


def meta_attr(s: str) -> str:
    """Values of the @page comment cannot contain a double quote."""
    return str(s).replace('"', "'").replace("-->", "")


def join_lt(items: list) -> str:
    items = [str(x) for x in items]
    if len(items) <= 1:
        return "".join(items)
    return ", ".join(items[:-1]) + " ir " + items[-1]


# ------------------------------------------------------------ size guide ----
# Orientation charts (labelled as such in the dialog). Rows are emitted only for the sizes the product has.
CLOTHING = {
    "vyrams": {
        # men's LT, EU and IT sizes share one number, so they are one column (no filler duplicates)
        "head": ["Dydis", "LT / EU / IT", "Krūtinė, cm", "Juosmuo, cm"],
        "rows": {
            "XS": ["44", "86-89", "72-75"],
            "S": ["46", "90-93", "76-79"],
            "M": ["48", "94-97", "80-83"],
            "L": ["50", "98-101", "84-87"],
            "XL": ["52", "102-105", "88-91"],
            "2XL": ["54", "106-109", "92-95"],
            "3XL": ["56", "110-113", "96-99"],
            "4XL": ["58", "114-117", "100-103"],
        },
        "how": [
            "Krūtinė: matuokite per plačiausią krūtinės vietą, juostą laikykite horizontaliai.",
            "Juosmuo: matuokite per natūralią liemens liniją, šiek tiek virš bambos.",
        ],
        "help": "Jei abejojate tarp dviejų dydžių, rinkitės didesnį: kai kurių prekės ženklų modeliai būna siauresnio kirpimo.",
    },
    "moterims": {
        "head": ["Dydis", "LT", "EU", "IT", "Krūtinė, cm", "Juosmuo, cm"],
        "rows": {
            "XS": ["40", "34", "38", "80-83", "62-65"],
            "S": ["42", "36", "40", "84-87", "66-69"],
            "M": ["44", "38", "42", "88-91", "70-73"],
            "L": ["46", "40", "44", "92-95", "74-77"],
            "XL": ["48", "42", "46", "96-99", "78-81"],
            "2XL": ["50", "44", "48", "100-103", "82-85"],
        },
        "how": [
            "Krūtinė: matuokite per plačiausią krūtinės vietą, juostą laikykite horizontaliai.",
            "Juosmuo: matuokite per siauriausią liemens vietą.",
        ],
        "help": "Jei abejojate tarp dviejų dydžių, rinkitės didesnį: kai kurių prekės ženklų modeliai būna siauresnio kirpimo.",
    },
}
SHOES = {
    "head": ["EU", "UK", "Pėdos ilgis, cm"],
    "rows": {
        "35": ["2,5", "22"], "36": ["3,5", "22,5"], "37": ["4", "23,5"], "38": ["5", "24"],
        "39": ["6", "25"], "40": ["6,5", "25,5"], "41": ["7,5", "26"], "42": ["8", "27"],
        "43": ["9", "27,5"], "44": ["9,5", "28,5"], "45": ["10,5", "29"], "46": ["11", "29,5"],
        "47": ["12", "30,5"],
    },
    "how": [
        "Atsistokite ant popieriaus lapo, pažymėkite kulno ir ilgiausio piršto galą.",
        "Išmatuokite atstumą centimetrais ir palyginkite su lentele. Matuokite vakare, kai pėda didžiausia.",
    ],
    "help": "Jei abejojate tarp dviejų dydžių, rinkitės didesnį.",
}


def size_guide_html(p: dict, meta: dict) -> str | None:
    group, gender = p["group"], p["gender"]
    if group == "avalyne":
        chart, kind = SHOES, "Avalynė"
    elif group == "drabuziai" and gender in CLOTHING:
        chart, kind = CLOTHING[gender], "Drabužiai"
    else:
        return None
    rows = []
    for s in p["sizes"]:
        key = s["value"] if s["value"] in chart["rows"] else size_label(s["label"])
        cells = chart["rows"].get(key)
        if not cells:
            continue
        na = "" if s["available"] else ' <span class="pdp-guide__na">nėra</span>'
        tds = "".join(f"<td>{esc(c)}</td>" for c in cells)
        rows.append(
            f'<tr data-size-row="{esc(s["value"])}"><th scope="row">{esc(size_label(s["label"]))}{na}'
            f'<span class="sr-only" data-size-row-sr></span></th>{tds}</tr>'
        )
    if not rows:
        return None
    head = "".join(f'<th scope="col">{esc(h)}</th>' for h in chart["head"])
    how = "".join(f"<li>{esc(h)}</li>" for h in chart["how"])
    who = f"{GENDER_LABEL.get(gender, '')}, {kind.lower()}" if gender in GENDER_LABEL else kind
    return (
        '<div class="pdp-guide">'
        f'<p class="pdp-guide__meta">{esc(p["brand"])} · {esc(who)}</p>'
        '<div class="pdp-guide__scroll" tabindex="0" role="region" aria-label="Dydžių lentelė, slinkite horizontaliai">'
        f'<table class="table pdp-guide__table"><caption class="sr-only">Dydžių atitikmenys: {esc(image_alt(p))}</caption>'
        f"<thead><tr>{head}</tr></thead><tbody>{''.join(rows)}</tbody></table></div>"
        '<p class="pdp-guide__note">Orientaciniai matmenys. Skirtingų prekės ženklų kirpimas gali šiek tiek skirtis.</p>'
        f'<div class="pdp-guide__how"><h3 class="pdp-guide__title">Kaip pasimatuoti</h3><ul>{how}</ul></div>'
        f'<p class="pdp-guide__help">{esc(chart["help"])} '
        f'Reikia patarimo? Skambinkite <a href="tel:{esc(meta["phone"])}">{esc(meta["phoneDisplay"]).replace(" ", NBSP)}</a>.</p>'
        "</div>"
    )


# ------------------------------------------------------------- markup ----


def price_html(p: dict, size: str = "", badge: bool = False, cls: str = "") -> str:
    """Mirror of BS.ui.priceHTML (core.js) so static and rendered prices are identical."""
    sz = f" price--{size}" if size else ""
    extra = f" {cls}" if cls else ""
    regular = p.get("regular") or p["price"]
    if regular > p["price"]:
        b = (f' <span class="badge badge--sale{" badge--lg" if size else ""}">{discount_label(p["discount"])}</span>' if badge else "")
        return (
            f'<p class="price price--sale{sz}{extra}"><span class="sr-only">Kaina su nuolaida: </span>'
            f'<span class="price__now">{fmt_price(p["price"])}</span><span class="sr-only">, ankstesnė kaina: </span>'
            f'<s class="price__old">{fmt_price(regular)}</s>{b}</p>'
        )
    return f'<p class="price{sz}{extra}"><span class="price__now">{fmt_price(p["price"])}</span></p>'


def gallery_html(p: dict) -> str:
    imgs = p["images"]
    n = len(imgs)
    alt = image_alt(p)
    thumbs, slides, dots = [], [], []
    wide = p["group"] == "avalyne"  # shoe packshots: wide subject with deep white margins, crop them in the stage
    for i, src in enumerate(imgs):
        cls = "pdp-img " + ("is-packshot" if is_packshot(p, i) else "is-photo") + (" is-wide" if wide and is_packshot(p, i) else "")
        a = alt if i == 0 else f"{alt}, {i + 1} nuotrauka iš {n}"
        cur = ' aria-current="true"' if i == 0 else ' aria-current="false"'
        thumbs.append(
            f'<a class="pdp-thumb" href="#pdp-foto-{i + 1}" data-pdp-thumb="{i}"{cur} aria-label="Rodyti {i + 1} nuotrauką iš {n}">'
            f'<img class="{cls}" src="{esc(src)}" alt="" width="800" height="1200" decoding="async"></a>'
        )
        load = 'loading="eager" fetchpriority="high"' if i == 0 else 'loading="lazy"'
        slides.append(
            f'<div class="pdp-slide" id="pdp-foto-{i + 1}" role="group" aria-roledescription="skaidrė" aria-label="{i + 1} iš {n}">'
            f'<button class="pdp-slide__zoom" type="button" data-pdp-open="{i}" aria-controls="pdp-lightbox" aria-haspopup="dialog">'
            f'<span class="sr-only">Padidinti nuotrauką: </span>'
            f'<img class="{cls}" src="{esc(src)}" data-zoom-src="{esc(src)}" alt="{esc(a)}" width="800" height="1200" {load} decoding="async"></button></div>'
        )
        dots.append(f'<span class="pdp-dot{" is-active" if i == 0 else ""}"></span>')
    badges = '<div class="pdp-gallery__badges"><span class="badge badge--new">Nauja</span></div>' if p.get("isNew") else ""
    nav = (
        '<div class="pdp-gallery__nav">'
        f'<button class="icon-btn icon-btn--solid" type="button" data-pdp-prev aria-label="Ankstesnė nuotrauka" disabled>{icon("arrow-left")}</button>'
        f'<button class="icon-btn icon-btn--solid" type="button" data-pdp-next aria-label="Kita nuotrauka"{" disabled" if n < 2 else ""}>{icon("arrow-right")}</button>'
        "</div>"
    ) if n > 1 else ""
    return (
        '<div class="pdp-gallery" data-pdp-gallery data-pdp-col>'
        f'<div class="pdp-gallery__thumbs" role="group" aria-label="Nuotraukų miniatiūros">{"".join(thumbs)}</div>'
        '<div class="pdp-gallery__stage">'
        '<div class="pdp-gallery__track" data-pdp-track role="region" aria-roledescription="karuselė" '
        f'aria-label="Nuotraukos: {esc(alt)}" data-lenis-prevent-horizontal>{"".join(slides)}</div>'
        f"{badges}"
        '<div class="pdp-gallery__ui">'
        f'<span class="pdp-gallery__count" data-pdp-count aria-hidden="true">1 / {n}</span>'
        f"{nav}"
        f'<button class="icon-btn icon-btn--solid pdp-gallery__expand" type="button" data-pdp-open="current" aria-controls="pdp-lightbox" aria-haspopup="dialog" aria-label="Rodyti nuotraukas visame ekrane">{icon("arrows-out-simple")}</button>'
        + (f'<div class="pdp-dots" aria-hidden="true">{"".join(dots)}</div>' if n > 1 else "")
        + "</div></div></div>"
    )


def lightbox_html(p: dict) -> str:
    imgs = p["images"]
    n = len(imgs)
    alt = image_alt(p)
    slides = []
    for i, src in enumerate(imgs):
        cls = "pdp-img " + ("is-packshot" if is_packshot(p, i) else "is-photo")
        a = alt if i == 0 else f"{alt}, {i + 1} nuotrauka iš {n}"
        slides.append(
            f'<figure class="pdp-lightbox__slide" role="group" aria-roledescription="skaidrė" aria-label="{i + 1} iš {n}">'
            f'<img class="{cls}" src="{esc(src)}" data-zoom-src="{esc(src)}" alt="{esc(a)}" width="800" height="1200" loading="lazy" decoding="async"></figure>'
        )
    dots = "".join(f'<span class="pdp-dot{" is-active" if i == 0 else ""}"></span>' for i in range(n))
    return (
        '<dialog class="pdp-lightbox" id="pdp-lightbox" aria-labelledby="pdp-lb-title" data-lenis-prevent>'
        f'<h2 class="sr-only" id="pdp-lb-title" tabindex="-1" autofocus>Nuotraukų peržiūra: {esc(alt)}</h2>'
        f'<div class="pdp-lightbox__track" data-pdp-lb-track role="region" aria-roledescription="karuselė" aria-label="Nuotraukos">{"".join(slides)}</div>'
        '<div class="pdp-lightbox__top">'
        f'<p class="pdp-lightbox__count" data-pdp-lb-count aria-hidden="true">1 / {n}</p>'
        f'<p class="pdp-lightbox__hint" aria-hidden="true">{icon("magnifying-glass-plus", "i--sm")}Spustelėkite, kad priartintumėte</p>'
        f'<button class="icon-btn icon-btn--solid icon-btn--lg" type="button" data-dialog-close>{icon("x", "i--lg")}<span class="sr-only">Uždaryti peržiūrą</span></button>'
        "</div>"
        + (
            f'<button class="icon-btn icon-btn--solid icon-btn--lg pdp-lightbox__nav pdp-lightbox__nav--prev" type="button" data-pdp-lb-prev aria-label="Ankstesnė nuotrauka">{icon("arrow-left")}</button>'
            f'<button class="icon-btn icon-btn--solid icon-btn--lg pdp-lightbox__nav pdp-lightbox__nav--next" type="button" data-pdp-lb-next aria-label="Kita nuotrauka">{icon("arrow-right")}</button>'
            f'<div class="pdp-dots pdp-lightbox__dots" aria-hidden="true">{dots}</div>'
            if n > 1 else ""
        )
        + '<p class="sr-only" aria-live="polite" data-pdp-lb-live></p>'
        "</dialog>"
    )


def sizes_html(p: dict, meta: dict, has_guide: bool) -> str:
    sizes = p["sizes"]
    if len(sizes) <= 1:
        phone = f'<a class="link" href="tel:{esc(meta["phone"])}">{esc(meta["phoneDisplay"]).replace(" ", NBSP)}</a>'
        mail = f'<a class="link" href="mailto:{esc(meta["email"])}">{esc(meta["email"])}</a>'
        return (
            '<div class="pdp-opt">'
            '<p class="pdp-opt__label"><span class="pdp-opt__key">Dydis</span><span class="pdp-opt__val">Vienas dydis</span></p>'
            f'<p class="pdp-opt__note">Klausimų dėl matmenų ar talpos? Skambinkite {phone} arba rašykite {mail}.</p>'
            "</div>"
        )
    chips = []
    for s in sizes:
        lab = esc(size_label(s["label"]))
        if s["available"]:
            chips.append(f'<button class="size-chip" type="button" data-size-value="{esc(s["value"])}" aria-pressed="false">{lab}</button>')
        else:
            chips.append(
                f'<button class="size-chip is-unavailable" type="button" aria-disabled="true" data-size-unavailable="{esc(s["value"])}" '
                f'aria-label="{lab}, šiuo metu nėra. Praneškite, kai atsiras">{lab}</button>'
            )
    missing = [s for s in sizes if not s["available"]]
    note = ""
    if missing:
        labels = [size_label(s["label"]) for s in missing]
        word = "dydžio" if len(labels) == 1 else "dydžių"
        note = (
            f'<p class="pdp-opt__note">{esc(join_lt(labels))} {word} šiuo metu nėra.'
            f' <span data-pdp-js-only><button class="pdp-textbtn" type="button" data-pdp-notify-open="{esc(missing[0]["value"])}" '
            f'aria-expanded="false" aria-controls="pdp-notify">Praneškite, kai atsiras</button></span></p>'
            '<div class="pdp-notify" id="pdp-notify" data-pdp-notify hidden>'
            '<form class="pdp-notify__form" data-pdp-notify-form novalidate>'
            f'<p class="pdp-notify__text">Įveskite el. pašto adresą ir pranešime, kai <strong data-pdp-notify-size>{esc(labels[0])}</strong> dydis vėl atsiras.</p>'
            '<div class="field" data-pdp-notify-field><label class="field__label" for="pdp-notify-email">El. pašto adresas</label>'
            '<div class="inline-form"><input class="field__input" id="pdp-notify-email" type="email" autocomplete="email" inputmode="email" '
            'placeholder="vardas@pastas.lt" aria-describedby="pdp-notify-hint pdp-notify-err">'
            '<button class="btn" type="submit">Pranešti</button></div>'
            '<p class="field__error" id="pdp-notify-err" hidden>Įveskite teisingą el. pašto adresą</p>'
            '<p class="field__hint pdp-notify__hint" id="pdp-notify-hint">El. paštą naudosime tik šiam pranešimui. '
            '<a href="#" data-demo>Privatumo politika</a></p></div></form>'
            f'<p class="field__success" data-pdp-notify-ok tabindex="-1" hidden>{icon("check-circle")}<span>Ačiū! Pranešime, kai '
            f'<span data-pdp-notify-size>{esc(labels[0])}</span> dydis vėl atsiras.</span></p>'
            "</div>"
        )
    guide = (
        f'<button class="pdp-guide-link" type="button" data-pdp-guide aria-controls="size-guide" aria-haspopup="dialog" data-pdp-js-only>'
        f'{icon("ruler", "i--sm")}<span>Dydžių lentelė</span></button>'
    ) if has_guide else ""
    return (
        '<div class="pdp-opt pdp-opt--size" data-pdp-size-block>'
        '<div class="pdp-opt__row">'
        '<p class="pdp-opt__label" id="pdp-size-label"><span class="pdp-opt__key">Dydis</span>'
        '<span class="pdp-opt__val" data-pdp-size-current></span></p>'
        f"{guide}</div>"
        f'<div class="sizes pdp-sizes" role="group" aria-labelledby="pdp-size-label" data-pdp-sizes{size_cols(sizes)}>{"".join(chips)}</div>'
        '<p class="field__error" id="pdp-size-error" data-pdp-size-error hidden>Pasirinkite dydį</p>'
        f"{note}</div>"
    )


def size_cols(sizes: list) -> str:
    """Equal grid columns for the size chips: one row up to 6 sizes, otherwise balanced rows.
    Long labels (W30 L32, 8-10 m.) fall back to the CSS auto-fill grid."""
    n = len(sizes)
    if n < 2 or any(len(size_label(s["label"])) > 4 for s in sizes):
        return ""
    rows = -(-n // 6)
    return f' style="--size-cols:{-(-n // rows)}"'


def color_siblings(p: dict, cat: dict) -> list:
    """Same model in other colours: same brand and the same SKU stem (Woo SKU = <model>_<colour code>)."""
    sku = p.get("sku") or ""
    if "_" not in sku:
        return []
    stem = sku.split("_")[0]
    return [
        x for x in cat["products"]
        if x["id"] != p["id"] and x["brandSlug"] == p["brandSlug"] and "_" in (x.get("sku") or "")
        and x["sku"].split("_")[0] == stem
    ]


def color_html(p: dict, cat: dict) -> str:
    color = (p.get("colors") or [{}])[0]
    if not color.get("name"):
        return ""
    sw = f'<span class="pdp-swatch" style="--swatch:{esc(color.get("hex") or "#ccc")}" aria-hidden="true" data-pdp-color-sw></span>' if color.get("hex") else ""
    label = (
        '<p class="pdp-opt__label"><span class="pdp-opt__key">Spalva</span>'
        f'<span class="pdp-opt__val">{sw}<span data-pdp-color-name>{esc(color["name"])}</span></span></p>'
    )
    sibs = color_siblings(p, cat)
    if not sibs:
        return f'<div class="pdp-opt">{label}</div>'
    pdp_ids = {int(x) for x in cat["collections"].get("pdp", [])}

    def thumb(x: dict) -> str:
        cls = "pdp-img " + ("is-packshot" if is_packshot(x, 0) else "is-photo")
        return f'<img class="{cls}" src="{esc(x["images"][0])}" alt="" width="800" height="1200" loading="lazy" decoding="async">'

    items = [
        f'<li><span class="pdp-color is-current" title="{esc(color["name"])}">{thumb(p)}'
        f'<span class="sr-only">{esc(color["name"])}, rodoma dabar</span></span></li>'
    ]
    for x in sibs:
        xc = (x.get("colors") or [{}])[0]
        name = xc.get("name") or x["title"]
        data = f' data-color-name="{esc(name)}"' + (f' data-color-hex="{esc(xc["hex"])}"' if xc.get("hex") else "")
        if x["id"] in pdp_ids:
            href, extra, sr = f'preke-{esc(x["slug"])}.html', "", f"{name} spalva, atidaryti prekės puslapį"
        else:
            href, extra, sr = f'#perziura-{x["id"]}', f' data-quick-view="{x["id"]}"', f"{name} spalva, greita peržiūra"
        items.append(
            f'<li><a class="pdp-color" href="{href}"{extra}{data} title="{esc(name)}">{thumb(x)}'
            f'<span class="sr-only">{esc(sr)}</span></a></li>'
        )
    n = len(sibs)
    names = [lc_first((x.get("colors") or [{}])[0].get("name") or x["title"]) if i else ((x.get("colors") or [{}])[0].get("name") or x["title"]) for i, x in enumerate(sibs)]
    return (
        '<div class="pdp-opt pdp-opt--color" data-pdp-colors>'
        f"{label}"
        f'<ul class="pdp-colors" role="list" aria-label="Spalvos">{"".join(items)}</ul>'
        f'<p class="pdp-colors__note">{"Kita spalva" if n == 1 else "Kitos spalvos"}: {esc(join_lt(names))}</p>'
        "</div>"
    )


def stock_html(p: dict) -> str:
    st = p.get("stock")
    if st is None or st > 3 or st < 1:
        return ""
    return f'<p class="stock-line">{"Liko paskutinis vienetas" if st == 1 else f"Liko tik {st}"}</p>'


def info_html(p: dict, cat: dict, has_guide: bool) -> str:
    meta = cat["meta"]
    facts = meta.get("shippingFacts") or {}
    ship_cost = fmt_price(facts.get("cost", 3))
    dispatch = facts.get("dispatch", "1-2 darbo dienas")
    on_sale = (p.get("regular") or p["price"]) > p["price"]
    brand_url = listing_url({"zenklas": p["brandSlug"]})
    color = (p.get("colors") or [{}])[0]

    price_extra = ""
    if on_sale:
        price_extra = (
            f'<p class="savings">Sutaupote <strong>{fmt_price(p["regular"] - p["price"])}</strong></p>'
            f'<p class="pdp-price__legal">Mažiausia kaina per 30 d. iki nuolaidos: {fmt_price(p["regular"])}. Kaina su PVM.</p>'
        )
    else:
        price_extra = '<p class="pdp-price__legal">Kaina su PVM.</p>'

    color_block = color_html(p, cat)

    wish = (
        f'<button class="icon-btn pdp-wish" type="button" data-wishlist="{p["id"]}" aria-pressed="false" '
        f'aria-label="Įsiminti: {esc(image_alt(p))}">{icon("heart", "i--lg i-off")}{icon("heart-fill", "i--lg i-on")}</button>'
    )

    paras = [x.strip() for x in dash_free(p.get("desc") or "").split("\n\n") if x.strip()]
    desc_html = "".join(f"<p>{esc(x)}</p>" for x in paras) or "<p>Aprašymas ruošiamas.</p>"
    specs = [("Prekės ženklas", p["brand"]), ("Kategorija", p["category"])]
    if color.get("name"):
        specs.append(("Spalva", color["name"]))
    for k, v in (p.get("specs") or {}).items():
        if k != "Spalva" and v:
            specs.append((k, v))
    specs_html = "".join(f"<div><dt>{esc(k)}</dt><dd>{esc(dash_free(v))}</dd></div>" for k, v in specs)
    details = "".join(f"<li>{esc(dash_free(d))}</li>" for d in p.get("details") or [])
    # Must agree with the payment marks (src/partials/payment-marks.html): Apple Pay, Google Pay, el. bankininkystė.
    wallets = [x for x in meta.get("payments") or [] if x != "El. bankininkystė"]
    pay_text = ", ".join(wallets) + " arba el. bankininkyste"

    return (
        '<div class="pdp-info" data-pdp-col><div class="pdp-info__inner">'
        '<header class="pdp-head">'
        f'<p class="pdp-head__brand"><a href="{esc(brand_url)}">{esc(p["brand"])}</a></p>'
        f'<h1 class="pdp-title">{esc(p["title"])}</h1>'
        "</header>"
        f'<div class="pdp-price">{price_html(p, "xl", badge=True)}{price_extra}</div>'
        f'<div class="pdp-opts">{color_block}{sizes_html(p, meta, has_guide)}</div>'
        '<div class="pdp-buy">'
        f"{stock_html(p)}"
        f'<div class="pdp-actions"><button class="btn btn--lg btn--block pdp-add" type="button" data-pdp-add>Į krepšelį</button>{wish}</div>'
        "</div>"
        '<ul class="pdp-facts" role="list">'
        f'<li class="pdp-fact">{icon("truck")}<div><p class="pdp-fact__title">Numatomas pristatymas: <strong data-pdp-eta>per 2-4 darbo dienas</strong></p>'
        f'<p class="pdp-fact__text">Išsiunčiame per {esc(dispatch)}.</p></div></li>'
        f'<li class="pdp-fact" data-pdp-ship>{icon("package")}<div><p class="pdp-fact__title" data-pdp-ship-text>'
        f"Pristatymas {ship_cost}, perkant 2 ir daugiau prekių nemokamai</p></div></li>"
        "</ul>"
        '<ul class="pdp-trust" role="list">'
        f"<li>{icon('seal-check', 'i--lg')}<span>100{NBSP}% originali prekė</span></li>"
        f"<li>{icon('arrow-counter-clockwise', 'i--lg')}<span>{meta.get('returnsDays', 14)} dienų grąžinimas</span></li>"
        f"<li>{icon('lock-simple', 'i--lg')}<span>Saugus atsiskaitymas</span></li>"
        "</ul>"
        '<ul class="pay-marks pay-marks--light pdp-pay" role="list" aria-label="Mokėjimo būdai"><!-- @include payment-marks --></ul>'
        f'<p class="pdp-sku">Prekės kodas: <span>{esc(p.get("sku") or p["id"])}</span></p>'
        '<div class="pdp-accs">'
        f'<details class="acc" open><summary class="acc__head">Aprašymas{ACC_ICON}</summary><div class="acc__body prose">{desc_html}</div></details>'
        f'<details class="acc"><summary class="acc__head">Detalės{ACC_ICON}</summary><div class="acc__body prose">'
        f'<dl class="pdp-specs">{specs_html}</dl>' + (f"<ul>{details}</ul>" if details else "") + "</div></details>"
        f'<details class="acc"><summary class="acc__head">Pristatymas ir grąžinimas{ACC_ICON}</summary><div class="acc__body prose"><ul>'
        f"<li>Išsiunčiame per {esc(dispatch)}. Numatomas pristatymas per 2-4 darbo dienas.</li>"
        f"<li>Pristatymas kainuoja {ship_cost}. Perkant 2 ir daugiau prekių pristatymas nemokamas.</li>"
        f"<li>Prekę galite grąžinti per {meta.get('returnsDays', 14)} dienų nuo jos gavimo.</li>"
        f"<li>Atsiskaityti galite {esc(pay_text)}.</li>"
        '</ul><p><a href="#" data-demo>Grąžinimo politika</a> · <a href="#" data-demo>Pristatymo sąlygos</a></p></div></details>'
        "</div>"
        "</div></div>"
    )


def carousel(list_name: str, label: str, cls: str = "", stagger: bool = True) -> str:
    st = " data-reveal-stagger" if stagger else ""
    return (
        f'<div class="carousel {cls}" data-carousel aria-label="{esc(label)}">'
        f'<div class="carousel__viewport"><ul class="carousel__track" data-pdp-list="{list_name}"{st}></ul></div>'
        '<div class="carousel__footer"><div class="carousel__progress"><span class="carousel__bar"></span></div>'
        '<span class="carousel__count"></span><div class="carousel__nav">'
        f'<button class="icon-btn icon-btn--outline" type="button" data-carousel-prev>{icon("arrow-left")}</button>'
        f'<button class="icon-btn icon-btn--outline" type="button" data-carousel-next>{icon("arrow-right")}</button>'
        "</div></div></div>"
    )


def sections_html(p: dict, cat: dict) -> str:
    brand = next((b for b in cat["brands"] if b["slug"] == p["brandSlug"]), None) or {}
    brand_name = p["brand"]
    brand_url = listing_url({"zenklas": p["brandSlug"]})
    cat_url = listing_url({"lytis": p["gender"], "kategorija": p["wooCategorySlug"]})
    arrow = icon("arrow-right", "btn__arrow")
    # The brand CTA opens the sale listing filtered by brand (parduotuve.html?zenklas=), so it is labelled and counted
    # as what it opens: the brand's offers in BS.collections.plp. The store-wide brand total is a separate quiet fact.
    plp_ids = {int(x) for x in cat["collections"].get("plp", [])}
    on_sale_n = sum(1 for x in cat["products"] if x["brandSlug"] == p["brandSlug"] and x["id"] in plp_ids)
    count = cta = ""
    if on_sale_n:
        count = (
            f'<p class="pdp-brand__count"><span class="pdp-brand__num">{fmt_num(on_sale_n)}</span>'
            f'<span>{plural(on_sale_n, ["pasiūlymas", "pasiūlymai", "pasiūlymų"])} išpardavime</span></p>'
        )
        cta = (
            f'<a class="btn btn--ghost" href="{esc(brand_url)}"><span>Žiūrėti visus<span class="sr-only"> {esc(brand_name)}</span> '
            f"pasiūlymus</span>{arrow}</a>"
        )
    fact = ""
    if brand.get("count"):
        n = brand["count"]
        fact = (
            f'<p class="pdp-brand__fact">Brandstore.lt parduotuvėje iš viso {fmt_num(n)} šio prekės ženklo '
            f'{plural(n, ["prekė", "prekės", "prekių"])}.</p>'
        )
    return (
        # Užbaikite įvaizdį
        '<section class="section section--tight pdp-section pdp-look" aria-labelledby="pdp-look-title" data-pdp-js-only>'
        '<div class="container"><div class="section-head"><div>'
        '<h2 class="h2 pdp-h2 section-head__title" id="pdp-look-title" data-split>Užbaikite įvaizdį</h2>'
        '<p class="section-head__text">Prekės, kurios dera prie šio modelio.</p></div></div>'
        '<ul class="product-grid pdp-look__grid" data-pdp-list="look" data-reveal-stagger></ul></div></section>'
        # Daugiau iš {brand}
        '<section class="section section--tight pdp-section pdp-brand" aria-labelledby="pdp-brand-title">'
        f'<p class="pdp-brand__word" aria-hidden="true"><span data-pdp-drift>{esc(brand_name)}</span></p>'
        '<div class="container pdp-brand__grid"><div class="pdp-brand__intro" data-reveal>'
        f'<h2 class="h2 pdp-h2" id="pdp-brand-title">Daugiau iš <em>{esc(brand_name)}</em></h2>'
        f"{count}{cta}{fact}"
        "</div>"
        f'<div class="pdp-brand__rail" data-pdp-js-only data-pdp-hide-empty>{carousel("brand", "Daugiau " + brand_name + " prekių")}</div>'
        "</div></section>"
        # Jums gali patikti
        '<section class="section section--tight pdp-section pdp-related" aria-labelledby="pdp-rel-title" data-pdp-js-only>'
        '<div class="container"><div class="section-head">'
        '<div><h2 class="h2 pdp-h2 section-head__title" id="pdp-rel-title" data-split>Jums gali patikti</h2></div>'
        f'<div class="section-head__aside"><a class="btn btn--link" href="{esc(cat_url)}">Žiūrėti visas{arrow}</a></div></div>'
        f'{carousel("related", "Jums gali patikti", "carousel--bleed")}</div></section>'
        # Neseniai žiūrėtos (shown by pdp.js when BS.recent has other products)
        '<section class="section section--tight pdp-section pdp-recent" aria-labelledby="pdp-recent-title" data-pdp-recent hidden>'
        '<div class="container"><div class="section-head">'
        '<div><h2 class="h2 pdp-h2 section-head__title" id="pdp-recent-title">Neseniai žiūrėtos</h2></div>'
        '<div class="section-head__aside"><button class="btn btn--link" type="button" data-pdp-recent-clear>Išvalyti istoriją</button></div></div>'
        f'{carousel("recent", "Neseniai žiūrėtos prekės", "carousel--bleed", stagger=False)}</div></section>'
    )


def bar_html(p: dict) -> str:
    sizes = p["sizes"]
    sel = ""
    if len(sizes) > 1:
        opts = ['<option value="" disabled selected>Pasirinkite dydį</option>']
        for s in sizes:
            lab = esc(size_label(s["label"]))
            opts.append(f'<option value="{esc(s["value"])}">{lab}</option>' if s["available"]
                        else f'<option value="{esc(s["value"])}" disabled>{lab}, nėra</option>')
        sel = (
            '<div class="select pdp-bar__select" data-pdp-bar-select>'
            f'<select aria-label="Dydis" data-pdp-bar-size>{"".join(opts)}</select>{icon("caret-down")}'
            '<p class="field__error pdp-bar__error" id="pdp-bar-err" data-pdp-bar-err hidden>Pasirinkite dydį</p></div>'
        )
    else:
        sel = '<p class="pdp-bar__one">Vienas dydis</p>'
    img = p["images"][0]
    cls = "pdp-img " + ("is-packshot" if is_packshot(p, 0) else "is-photo")
    return (
        '<div class="pdp-bar" data-pdp-bar role="region" aria-label="Greitas pirkimas" inert>'
        '<div class="pdp-bar__inner container">'
        f'<div class="pdp-bar__product"><span class="pdp-bar__thumb"><img class="{cls}" src="{esc(img)}" alt="" width="800" height="1200" loading="lazy" decoding="async"></span>'
        f'<span class="pdp-bar__text"><span class="pdp-bar__brand">{esc(p["brand"])}</span><span class="pdp-bar__title">{esc(p["title"])}</span></span></div>'
        f'<div class="pdp-bar__price">{price_html(p, "lg")}</div>'
        f"{sel}"
        '<button class="btn pdp-bar__add" type="button" data-pdp-bar-add>Į krepšelį</button>'
        "</div></div>"
    )


def json_ld(p: dict, cat_url: str, gender_url: str) -> str:
    color = (p.get("colors") or [{}])[0]
    paras = [x.strip() for x in dash_free(p.get("desc") or "").split("\n\n") if x.strip()]
    available = any(s["available"] for s in p["sizes"])
    name = image_alt(p)
    data = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "Product",
                "name": name,
                "image": p["images"],
                "description": " ".join(paras),
                "sku": p.get("sku"),
                "brand": {"@type": "Brand", "name": p["brand"]},
                "color": color.get("name"),
                "category": f"{GENDER_LABEL.get(p['gender'], '')} > {GROUP_LABEL.get(p['group'], '')} > {p['category']}",
                "offers": {
                    "@type": "Offer",
                    "url": p.get("permalink"),
                    "priceCurrency": "EUR",
                    "price": f"{p['price']:.2f}",
                    "availability": "https://schema.org/InStock" if available else "https://schema.org/OutOfStock",
                    "itemCondition": "https://schema.org/NewCondition",
                    "seller": {"@type": "Organization", "name": "Brandstore.lt"},
                },
            },
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {"@type": "ListItem", "position": 1, "name": "Pradžia", "item": "index.html"},
                    {"@type": "ListItem", "position": 2, "name": GENDER_LABEL.get(p["gender"], ""), "item": gender_url},
                    {"@type": "ListItem", "position": 3, "name": p["category"], "item": cat_url},
                    {"@type": "ListItem", "position": 4, "name": p["title"]},
                ],
            },
        ],
    }
    body = json.dumps(data, ensure_ascii=False, indent=1).replace("</", "<\\/")
    return (
        "<!-- Demo: schema.org Product + BreadcrumbList from catalog.json (WooCommerce/Yoast output this on the live site) -->\n"
        f'<script type="application/ld+json">\n{body}\n</script>'
    )


def render_page(p: dict, cat: dict) -> str:
    meta = cat["meta"]
    gender = p["gender"]
    glabel = GENDER_LABEL.get(gender, "")
    on_sale = (p.get("regular") or p["price"]) > p["price"]
    gender_url = listing_url({"lytis": gender})
    cat_url = listing_url({"lytis": gender, "kategorija": p["wooCategorySlug"]})
    name = image_alt(p)
    title = f"{name} | Brandstore.lt"
    desc = f"{name} už {fmt_price(p['price'])}"
    if on_sale:
        desc += f" vietoj {fmt_price(p['regular'])} ({discount_label(p['discount'])})"
    desc += f". Originali prekė, išsiunčiame per {meta.get('shippingFacts', {}).get('dispatch', '1-2 darbo dienas')}, 14 dienų grąžinimas."
    img0 = p["images"][0]
    guide = size_guide_html(p, meta)

    head = (
        f'<!-- @page title="{meta_attr(title)}" description="{meta_attr(desc)}" body="page-pdp" header="solid" '
        f'css="pdp" js="pdp" nav="{gender}" mobilebar="off" preload="{img0}" og_image="{img0}" -->'
    )
    crumbs = (
        '<nav class="breadcrumbs pdp-crumbs" aria-label="Naršymo kelias"><ol>'
        '<li><a href="index.html">Pradžia</a></li>'
        f'<li><a href="{esc(gender_url)}">{esc(glabel)}</a></li>'
        f'<li><a href="{esc(cat_url)}">{esc(p["category"])}</a></li>'
        f'<li><span aria-current="page">{esc(p["title"])}</span></li>'
        "</ol></nav>"
    )
    back = (
        f'<a class="btn btn--link btn--sm pdp-back" href="{esc(cat_url)}" data-pdp-back hidden>'
        f'{icon("arrow-left", "i--sm")}<span>Atgal į rezultatus</span></a>'
    )
    template = f'<template id="pdp-size-guide">{guide}</template>' if guide else ""
    return "\n".join([
        head,
        MARKER,
        json_ld(p, cat_url, gender_url),
        f'<div class="pdp" data-pdp="{p["id"]}" data-pdp-group="{esc(p["group"])}">',
        '<section class="pdp-main" aria-label="Prekė">',
        '<div class="container">',
        f'<div class="pdp-topline">{crumbs}{back}</div>',
        f'<div class="pdp-grid">{gallery_html(p)}{info_html(p, cat, bool(guide))}</div>',
        "</div>",
        "</section>",
        sections_html(p, cat),
        "</div>",
        lightbox_html(p),
        bar_html(p),
        template,
        "",
    ])


def main() -> None:
    cat = json.loads(CATALOG.read_text(encoding="utf-8"))
    by_id = {p["id"]: p for p in cat["products"]}
    wanted = set()
    for pid in cat["collections"].get("pdp", []):
        p = by_id.get(int(pid))
        if not p:
            print(f"  pdp: product {pid} not found in catalog.json, skipped")
            continue
        out = PAGES / f"preke-{p['slug']}.html"
        wanted.add(out.name)
        text = render_page(p, cat)
        if "—" in text:
            raise SystemExit(f"pdp: em dash in generated {out.name}")
        old = out.read_text(encoding="utf-8") if out.exists() else None
        if old != text:
            out.write_text(text, encoding="utf-8")
            print(f"  pdp: wrote src/pages/{out.name}")
        else:
            print(f"  pdp: unchanged src/pages/{out.name}")
    # remove pages this generator made for products that are no longer in BS.collections.pdp
    for f in PAGES.glob("preke-*.html"):
        if f.name not in wanted and MARKER in f.read_text(encoding="utf-8"):
            f.unlink()
            print(f"  pdp: removed stale src/pages/{f.name}")


if __name__ == "__main__":
    main()
